---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpro1-payment
  namespace: cpro1-app-ns
  labels:
    app: cpro1-application
    subname: payment
spec:
  selector:
    matchLabels:
      app: cpro1-application
      subname: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: cpro1-application
        subname: payment          
    spec:
      containers:
        - name: container-payment
          image: "gandigit/cpro-payment:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9033
              protocol: TCP
            - name: https
              containerPort: 8082
          env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: service.url.commission
            valueFrom:
              configMapKeyRef:
                name: cpro1-config-map
                key: service.url.commission
---
apiVersion: v1
kind: Service
metadata:
  name: cpro1-payment
  namespace: cpro1-app-ns
  labels:
    app: cpro1-application
    subname: payment
  annotations:
    mcm.ibm.com/service-discovery: "{}"            
spec:
  type: ClusterIP
  ports:
    - name: my-http
      port: 9090
      targetPort: 9033
  selector:
    app: cpro1-application
    subname: payment
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cpro1-payment
  namespace: cpro1-app-ns
  labels:
    app: cpro1-application
    subname: payment
spec:
  path: /
  to:
    kind: Service
    name: cpro1-payment
    weight: 100
  port:
    targetPort: my-http